-- =============================================================================
-- FinSight - Esquema completo da base de dados (PostgreSQL)
-- =============================================================================
-- Gerado a partir das migrations EF Core do projeto GestaoDespesas:
--   * 20260226191251_TestData          (esquema inicial)
--   * 20260226210840_testAcc           (migration vazia / placeholder)
--   * 20260310120000_AddReceitasTable  (tabela Receitas)
--
-- Este ficheiro é a referência completa do esquema. Aplicar a uma base de
-- dados vazia produz exatamente o mesmo estado que correr
-- `dotnet ef database update` no projeto.
-- =============================================================================

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- -----------------------------------------------------------------------------
-- Migration: 20260226191251_TestData
-- -----------------------------------------------------------------------------
START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Categorias" (
    "CategoriaId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(60) NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Categorias" PRIMARY KEY ("CategoriaId")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserProfiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "SalarioMensal" numeric(18,2) NOT NULL,
    "LimitePercentual" integer NOT NULL,
    "ReceberAlertas" boolean NOT NULL,
    CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserProfiles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Despesas" (
    "DespesaId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Descricao" character varying(120) NOT NULL,
    "Valor" numeric NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    "CategoriaId" integer NOT NULL,
    "Observacoes" text,
    "UserId" text NOT NULL,
    "CategoriaId1" integer,
    CONSTRAINT "PK_Despesas" PRIMARY KEY ("DespesaId"),
    CONSTRAINT "FK_Despesas_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("CategoriaId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Despesas_Categorias_CategoriaId1" FOREIGN KEY ("CategoriaId1") REFERENCES "Categorias" ("CategoriaId")
);

CREATE TABLE "Orcamentos" (
    "OrcamentoId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Ano" integer NOT NULL,
    "Mes" integer NOT NULL,
    "CategoriaId" integer NOT NULL,
    "Limite" numeric NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Orcamentos" PRIMARY KEY ("OrcamentoId"),
    CONSTRAINT "FK_Orcamentos_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("CategoriaId") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE UNIQUE INDEX "IX_Categorias_UserId_Nome" ON "Categorias" ("UserId", "Nome");

CREATE INDEX "IX_Despesas_CategoriaId" ON "Despesas" ("CategoriaId");

CREATE INDEX "IX_Despesas_CategoriaId1" ON "Despesas" ("CategoriaId1");

CREATE INDEX "IX_Orcamentos_CategoriaId" ON "Orcamentos" ("CategoriaId");

CREATE UNIQUE INDEX "IX_UserProfiles_UserId" ON "UserProfiles" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260226191251_TestData', '8.0.24');

COMMIT;

-- -----------------------------------------------------------------------------
-- Migration: 20260226210840_testAcc (sem alterações de esquema)
-- -----------------------------------------------------------------------------
START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260226210840_testAcc', '8.0.24');

COMMIT;

-- -----------------------------------------------------------------------------
-- Migration: 20260310120000_AddReceitasTable
-- -----------------------------------------------------------------------------
START TRANSACTION;

CREATE TABLE "Receitas" (
    "ReceitaId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Descricao" character varying(120) NOT NULL,
    "Valor" numeric(18,2) NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    "Tipo" character varying(60) NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Receitas" PRIMARY KEY ("ReceitaId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260310120000_AddReceitasTable', '8.0.24');

COMMIT;
